{
  "severity": "HIGH", 
  "created_at": "2006-10-10T04:06:00Z", 
  "description": "Buffer overflow in the repr function in Python 2.3 through 2.6 before 20060822 allows context-dependent attackers to cause a denial of service and possibly execute arbitrary code via crafted wide character UTF-32/UCS-4 strings to certain scripts.", 
  "updated_at": "2018-10-17T21:40:00Z", 
  "packages": [
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-mpz", 
        "sha256": "fa9560d6b1f1bf849eae5676fabd0f3899b9cc52345b9b683e54f68413df3615", 
        "sha1": "b77ea13bf9e68083066e75b4a20245e8851ffb25", 
        "md5": "5fcd7972c7cdb88ba861570d200d1373", 
        "arch": "I386", 
        "filename": "python2.3-mpz_2.3.5-3sarge1_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-dev", 
        "sha256": "60616ecc8b504ad2db6fe4ec2a40cbb2129d82bb444ccf335535abc7af32e04e", 
        "sha1": "258b22b6e41db665d7047e13adb0b2eaa76f6bbd", 
        "md5": "acb2012f860ea2394ce4d59d208e0fff", 
        "arch": "AMD64", 
        "filename": "python2.3-dev_2.3.5-3sarge1_amd64.deb"
      }
    }, 
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-tk", 
        "sha256": "f08fef0aa65c8251c1617af5c745aeb6680d0a062982a9b209fc3726bbc82ce9", 
        "sha1": "af24f757820fcef65504a6625914182d07ac14cc", 
        "md5": "43f9cbc02557f8ec84c6b5fa0255957f", 
        "arch": "AMD64", 
        "filename": "python2.3-tk_2.3.5-3sarge1_amd64.deb"
      }
    }, 
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-gdbm", 
        "sha256": "64e475eebe60144fe3b257c412249cf6454adb46536eb4b62e1a404592a36bc4", 
        "sha1": "d2f106a2b4894e61124fdb51ff4e9a552e9512c7", 
        "md5": "ad2698329ba7c99eac5eaa6b1a590b94", 
        "arch": "I386", 
        "filename": "python2.3-gdbm_2.3.5-3sarge1_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-dev", 
        "sha256": "cc4da3aedb9df63606c96c8d7f5acda132add483242fc4197e1c098ebdd3deb7", 
        "sha1": "46fb421e8b7f5bc93f0e26f56d1d22ac8214a8d2", 
        "md5": "fd12921c4b72a2bc5c09c13cf61fff5f", 
        "arch": "I386", 
        "filename": "python2.3-dev_2.3.5-3sarge1_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-gdbm", 
        "sha256": "0a1b121b76d9de1db352e6c262af1249c9b314a7c1022dbcf25f711cacf24e4b", 
        "sha1": "4eb7e27afe2b2e03e02188e278f88356cb3384d4", 
        "md5": "349f90ebf6e00a7ec83e3c3414940d9a", 
        "arch": "AMD64", 
        "filename": "python2.3-gdbm_2.3.5-3sarge1_amd64.deb"
      }
    }, 
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-tk", 
        "sha256": "a4071aa482a142d897b93f82ee8b11a1a4d2d5888ab97e985da64504cde6cc6e", 
        "sha1": "eaa05499babe2842f3645648f15e756c29a1e156", 
        "md5": "93b3439f064954d9b9a7734418f25945", 
        "arch": "I386", 
        "filename": "python2.3-tk_2.3.5-3sarge1_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "2.3.5-3sarge1", 
      "name": "python2.3", 
      "source": "DSA", 
      "fixed_version": "2.3.5-3sarge2", 
      "uid": "DSA-1198-1", 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python2.3", 
        "version": "2.3.5-3sarge1", 
        "name": "python2.3-mpz", 
        "sha256": "dea874062961f6cb2af09462f390c39aebb09f444eecfa0da483c3af3a12d6ee", 
        "sha1": "170901ccc70ef4bd0f758c67b806d855ee475426", 
        "md5": "94326ce547a1d484713f89baee196f05", 
        "arch": "AMD64", 
        "filename": "python2.3-mpz_2.3.5-3sarge1_amd64.deb"
      }
    }, 
    {
      "vulnerable_version": "2.4.1-2", 
      "name": "python2.4", 
      "source": "DSA", 
      "fixed_version": "2.4.1-2sarge1", 
      "uid": "DSA-1197-1", 
      "fixed_package": {
        "source": "python2.4", 
        "version": "2.4.1-2sarge1", 
        "name": "python2.4-tk", 
        "sha256": "5f8db1d51e74f31273aa901e671e34ab0420ebdd9e6cab4651be35609ab1cd79", 
        "sha1": "7cc0b89bcb1688c11b0773bcfa5ee94b7e8dffa0", 
        "md5": "dc99596f18cf8d10a52d0d81083b62cc", 
        "arch": "I386", 
        "filename": "python2.4-tk_2.4.1-2sarge1_i386.deb"
      }, 
      "vulnerable_package": {
        "source": "python2.4", 
        "version": "2.4.1-2", 
        "name": "python2.4-tk", 
        "sha256": "c7e019c91e9dd927118edf806915c659e0ca64915fe577d49e8bb8f596642b35", 
        "sha1": "41a800120c09ea0eeeab4372ac8bfb11543669c7", 
        "md5": "d2030283dae56e4f9632fde5ec03c85d", 
        "arch": "I386", 
        "filename": "python2.4-tk_2.4.1-2_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "2.4.1-2", 
      "name": "python2.4", 
      "source": "DSA", 
      "fixed_version": "2.4.1-2sarge1", 
      "uid": "DSA-1197-1", 
      "fixed_package": {
        "source": "python2.4", 
        "version": "2.4.1-2sarge1", 
        "name": "python2.4-dbg", 
        "sha256": "0705e7250e36a96b02119d3a020de6daf7c59089c9ff5ad97023758fcd1a07c4", 
        "sha1": "950b0689809fe3cdec4f1b52d39857cd491e58ab", 
        "md5": "67a1ae83b45af4fcd0ea04d27df0caab", 
        "arch": "I386", 
        "filename": "python2.4-dbg_2.4.1-2sarge1_i386.deb"
      }, 
      "vulnerable_package": {
        "source": "python2.4", 
        "version": "2.4.1-2", 
        "name": "python2.4-dbg", 
        "sha256": "14d250dd71453de19ff681ce12193990f9579ab1ba1d4c055b15cfe08784e0c1", 
        "sha1": "63cdb614ece8b444f8d4c676e2751afb9e0f2f05", 
        "md5": "b701b212d55f7e8e522158d3607cf59d", 
        "arch": "I386", 
        "filename": "python2.4-dbg_2.4.1-2_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "2.4.1-2", 
      "name": "python2.4", 
      "source": "DSA", 
      "fixed_version": "2.4.1-2sarge1", 
      "uid": "DSA-1197-1", 
      "fixed_package": {
        "source": "python2.4", 
        "version": "2.4.1-2sarge1", 
        "name": "python2.4-gdbm", 
        "sha256": "e2fa0ad1d17e1c148793426185f118c08bde30444423b23b6c551a6f8e39c1ac", 
        "sha1": "131fbb43da437ec733f02216528072b7f298f41d", 
        "md5": "76de5a0d786eed213f22b32b9dcd8057", 
        "arch": "I386", 
        "filename": "python2.4-gdbm_2.4.1-2sarge1_i386.deb"
      }, 
      "vulnerable_package": {
        "source": "python2.4", 
        "version": "2.4.1-2", 
        "name": "python2.4-gdbm", 
        "sha256": "52653af10b640a8ba66e92461e8bad4af518267108bc2225d297c61f4f268744", 
        "sha1": "7e6557b4c6b256dcef0fa003a58b293161145f81", 
        "md5": "c6016c6354deebd2cd2b92cc315dc8bb", 
        "arch": "I386", 
        "filename": "python2.4-gdbm_2.4.1-2_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "2.4.1-2", 
      "name": "python2.4", 
      "source": "DSA", 
      "fixed_version": "2.4.1-2sarge1", 
      "uid": "DSA-1197-1", 
      "fixed_package": {
        "source": "python2.4", 
        "version": "2.4.1-2sarge1", 
        "name": "python2.4-dev", 
        "sha256": "92b32ae9597746797d599665f2405d431fac9a8f8505d7f134e87b4a10568207", 
        "sha1": "0dc6bc31371deebdc9d7cfa72ac490916b26e4e9", 
        "md5": "a4c6fed23893734aa0b745ebcdf0506b", 
        "arch": "I386", 
        "filename": "python2.4-dev_2.4.1-2sarge1_i386.deb"
      }, 
      "vulnerable_package": {
        "source": "python2.4", 
        "version": "2.4.1-2", 
        "name": "python2.4-dev", 
        "sha256": "39b3d295d7f1973b4f5cc3818880ed5976af8e4cb26be1ea6e3c41ee705c93b8", 
        "sha1": "578c24d0ca4f10f55f2b5a5a93eb705ea9258c03", 
        "md5": "2c4ac6fe1fee14dfd68b55e5bf03979e", 
        "arch": "I386", 
        "filename": "python2.4-dev_2.4.1-2_i386.deb"
      }
    }
  ], 
  "name": "CVE-2006-4980"
}