{
  "severity": "MEDIUM", 
  "created_at": "2014-04-23T15:55:00Z", 
  "description": "The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"", 
  "updated_at": "2017-01-07T02:59:00Z", 
  "packages": [
    {
      "vulnerable_version": "1.6.1-2", 
      "name": "python-django", 
      "source": "USN", 
      "fixed_version": "1.6.1-2ubuntu0.1", 
      "uid": null, 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": null, 
        "version": "1.6.1-2", 
        "name": "python-django", 
        "sha256": "a40f2f1d5c5cb2c5d0ff6b5735ebcd8859fc6668850712fe2f201fb7180441d7", 
        "sha1": "da2f9347245a6c6a344869b147791192e31f4f92", 
        "md5": "9ca403adee93d5ca2d36f47eb3348908", 
        "arch": "ALL", 
        "filename": "python-django_1.6.1-2_all.deb"
      }
    }, 
    {
      "vulnerable_version": "1.6.1-2", 
      "name": "python-django", 
      "source": "USN", 
      "fixed_version": "1.6.1-2ubuntu0.1", 
      "uid": null, 
      "fixed_package": null, 
      "vulnerable_package": {
        "source": "python-django", 
        "version": "1.6.1-2", 
        "name": "python-django-doc", 
        "sha256": "fa9b91d5245e5c42bfb3bc8139903b8b795c514420dfc2b2249a062e20c4eb88", 
        "sha1": "94592f5e731337ea98a6c952a69371800050faac", 
        "md5": "6af8e9a083241075c5de496876e84b27", 
        "arch": "ALL", 
        "filename": "python-django-doc_1.6.1-2_all.deb"
      }
    }, 
    {
      "vulnerable_version": "1.3.1-4ubuntu1.8", 
      "name": "python-django", 
      "source": "USN", 
      "fixed_version": "1.3.1-4ubuntu1.9", 
      "uid": null, 
      "fixed_package": {
        "source": "python-django", 
        "version": "1.3.1-4ubuntu1.9", 
        "name": "python-django-doc", 
        "sha256": "57399ac9a4a72fcc56100cf04c9b64080e2aee7341619600d880fc314e0abaa4", 
        "sha1": "94f9613878832b44e19ffff40f3498c635768f05", 
        "md5": "e1a36ec02dd8ef6a1174a8a2a31059c1", 
        "arch": "ALL", 
        "filename": "python-django-doc_1.3.1-4ubuntu1.9_all.deb"
      }, 
      "vulnerable_package": {
        "source": "python-django", 
        "version": "1.3.1-4ubuntu1.8", 
        "name": "python-django-doc", 
        "sha256": "3780ffa41f8b4507c953a7dc468edaec77a47ef7ddcb5fc04f89542cacc7f49e", 
        "sha1": "c5873d6c52e5a54aa68b24d02aadac94e17e6866", 
        "md5": "09d408528cf6d795055d5ace4c848666", 
        "arch": "ALL", 
        "filename": "python-django-doc_1.3.1-4ubuntu1.8_all.deb"
      }
    }, 
    {
      "vulnerable_version": "1.3.1-4ubuntu1.8", 
      "name": "python-django", 
      "source": "USN", 
      "fixed_version": "1.3.1-4ubuntu1.9", 
      "uid": null, 
      "fixed_package": {
        "source": null, 
        "version": "1.3.1-4ubuntu1.9", 
        "name": "python-django", 
        "sha256": "ddaae061a6b365fcc205ddae9d26af70057c2bb8d06c036a3b61681063b1ab5f", 
        "sha1": "35eaf09cbd48559776f7ad78005d2fd1a4132e57", 
        "md5": "331f679311585ef9a6f9e5eb869cc136", 
        "arch": "ALL", 
        "filename": "python-django_1.3.1-4ubuntu1.9_all.deb"
      }, 
      "vulnerable_package": {
        "source": null, 
        "version": "1.3.1-4ubuntu1.8", 
        "name": "python-django", 
        "sha256": "e4abf9821a0f246707f23df97e48e752376ee6c1e6054b07376d3602dc746ed6", 
        "sha1": "e0622aab6fd82b7ea4cef7f6de2e0829c58659d7", 
        "md5": "2ef290dec3036468a5501b7d77c8ddf0", 
        "arch": "ALL", 
        "filename": "python-django_1.3.1-4ubuntu1.8_all.deb"
      }
    }, 
    {
      "vulnerable_version": "1.6.1-2", 
      "name": "python-django", 
      "source": "USN", 
      "fixed_version": "1.6.1-2ubuntu0.1", 
      "uid": null, 
      "fixed_package": {
        "source": null, 
        "version": "1.6.1-2ubuntu0.1", 
        "name": "python-django", 
        "sha256": "0542d6d818215de09e03c79a9a7ec910b287812619fcc986571b48dfd7aef54f", 
        "sha1": "6f3851d2e3b4de2c3e232797c8558030f4d4b89b", 
        "md5": "154419f1e6c985dd986aac21d365b1e9", 
        "arch": "ALL", 
        "filename": "python-django_1.6.1-2ubuntu0.1_all.deb"
      }, 
      "vulnerable_package": {
        "source": null, 
        "version": "1.6.1-2", 
        "name": "python-django", 
        "sha256": "a40f2f1d5c5cb2c5d0ff6b5735ebcd8859fc6668850712fe2f201fb7180441d7", 
        "sha1": "da2f9347245a6c6a344869b147791192e31f4f92", 
        "md5": "9ca403adee93d5ca2d36f47eb3348908", 
        "arch": "ALL", 
        "filename": "python-django_1.6.1-2_all.deb"
      }
    }, 
    {
      "vulnerable_version": "1.6.1-2", 
      "name": "python-django", 
      "source": "USN", 
      "fixed_version": "1.6.1-2ubuntu0.1", 
      "uid": null, 
      "fixed_package": {
        "source": "python-django", 
        "version": "1.6.1-2ubuntu0.1", 
        "name": "python-django-doc", 
        "sha256": "aa9fd765429600636be5d78fb75fa46f58bab0865fdea054440c6e5d375fb0da", 
        "sha1": "494d2d7e13807b537e3a61b16df79a6137399839", 
        "md5": "bcb7e47e2cbc8823d1f95e731f245a1a", 
        "arch": "ALL", 
        "filename": "python-django-doc_1.6.1-2ubuntu0.1_all.deb"
      }, 
      "vulnerable_package": {
        "source": "python-django", 
        "version": "1.6.1-2", 
        "name": "python-django-doc", 
        "sha256": "fa9b91d5245e5c42bfb3bc8139903b8b795c514420dfc2b2249a062e20c4eb88", 
        "sha1": "94592f5e731337ea98a6c952a69371800050faac", 
        "md5": "6af8e9a083241075c5de496876e84b27", 
        "arch": "ALL", 
        "filename": "python-django-doc_1.6.1-2_all.deb"
      }
    }
  ], 
  "name": "CVE-2014-0472"
}